name = "gloap"
version = "1.0.0"

description = "A CoAP library in Gleam."
licences = ["Apache-2.0"]
repository = { type = "github", user = "KavanPrice", repo = "https://github.com/KavanPrice/gloap.git" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
